name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier . --write 
      # - run: |
      #     eslint 